apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: alicek106-csr
spec:
  signerName: kubernetes.io/kube-apiserver-client
  groups:
  - system:authenticated
  request: <CSR>
  usages:
  - digital signature
  - key encipherment
  - client auth
