apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
kubernetesVersion: v1.32.0
clusterName: kubernetes
apiServer:
  extraArgs:
  - name: authorization-mode
    value: Node,RBAC
certificatesDir: /etc/kubernetes/pki
controllerManager: {}
etcd:
  local:
    dataDir: /var/lib/etcd
networking:
  dnsDomain: cluster.local
  podSubnet: ${pod_subnet}
  serviceSubnet: 10.96.0.0/12
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
bootstrapTokens:
- description: kubeadm bootstrap token
  groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: "${token}"
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
timeouts:
  controlPlaneComponentHealthCheck: 4m0s
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  name: NODE_HOSTNAME
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
serverTLSBootstrap: true
cgroupDriver: systemd